### ISSUE TITLE
How to Get cookie for config.h

### ISSUE THREAD

**Issue by manavchaudhary1** [baconator696/Recu-Download#1]

**Comment by baconator696** [comment]
Open the Developer Tools in chrome, then open the network network tab, and at the top click filter by Doc. Now refresh the current page, and in the network tab select one of the network requests, under Request Headers, you'll be able to get the Cookie and User-Agent

**Comment by lolsas2** [comment]
> Open the Developer Tools in chrome, then open the network network tab, and at the top click filter by Doc. Now refresh the current page, and in the network tab select one of the network requests, under Request Headers, you'll be able to get the Cookie and User-Agent

i did everything you've said. but when i run the code in the powershell, it says 

PS E:\scrawler\recu\Recu-Download> .\recurbate.exe -config config.json
>>
Recu
please modify config.json
PS E:\scrawler\recu\Recu-Download>

**Comment by uptoboxcom2** [comment]
Hello, I tried your program on windows 10,
it works, but the download speed of 1.4 MB cannot increase more than that,
so i suggest you find us a way to play the video on the media player
for example (PotPlayer or VLC or KMPlayer)
i am waiting for you and thank you for everything
