### ISSUE TITLE
Is it possible to download vids that are labeled "video unavailable" 

### ISSUE THREAD

**Issue by yud1018715** [baconator696/Recu-Download#11]
So I've come across your page and I was wondering if I could download videos that are labeled as "video unavailable" using your program with their premium plan that I'm thinking about buying. I know it's possible to do since some guy did for me when I use to request unavailable videos for him to do and he would do it successfully, but he was using his own setup I was just asking to know by chance if yours could help me achieve the same thing he did since he's gone offline now and I'm trying to learn what he does to download those videos that are "unavailable".

**Comment by brad86m** [comment]
> my program used to be able to download unavailable videos, but they updated the website and killed it. Now only the ultimate account can get those videos

Is this still the case ? Looking at the blank thumbnails of the unavailable videos shows as 0 views on all of them. Would love to be able to pull them from the site. I'm only on the trial period of Premium.
