### ISSUE TITLE
modify config.json

### ISSUE THREAD

**Issue by lolsas2** [baconator696/Recu-Download#13]
i did everything you've said. but when i run the code in the powershell, it says

PS E:\scrawler\recu\Recu-Download> .\recurbate.exe -config config.json

Recu
please modify config.json
PS E:\scrawler\recu\Recu-Download>

i sign in in the recu page and in the dev settings, under the network tab filtered doc type. after selecting "play" document, i reached response cookies and user agent info. i copy-paste the info to your config file. but notting happened. i can share my config.json file if you want

**Comment by manavchaudhary1** [comment]
Try running 
```
./recurbate
```
only , & make sure the link is valid and cookie is fresh.
We don't have to specify -config arg to execute until the config.json is in same folder.

**Comment by manavchaudhary1** [comment]
I tried recreating your issue but i'm getting 
> status code: 403
Cloudflare Blocked: Failed on url: https://recu.me/*****

**Comment by lolsas2** [comment]
> I tried recreating your issue but i'm getting
> 
> > status code: 403
> > Cloudflare Blocked: Failed on url: https://recu.me/*****

![Ekran Alıntısı](https://github.com/user-attachments/assets/81ec3e80-d45a-49c7-af3d-67e09a6ec116)

What's wrong with this code?
After this, program says " character is invalid.

**Comment by manavchaudhary1** [comment]
Format is wrong use this one , paste your User-Agent key
```
{
	"urls": [
	""
	],
	"header": {
		"Cookie": "",
		"User-Agent": ""
	}
}
```

**Comment by baconator696** [comment]
> > I tried recreating your issue but i'm getting
> > > status code: 403
> > > Cloudflare Blocked: Failed on url: https://recu.me/*****
> 
> What's wrong with this code? After this, program says " character is invalid.

When you run the program for the first time, it will create a config.json file in the working directory, just modify that one by just pasting in your links and headers. I would just delete your config.json file and start from scratch considering you just added random brackets everywhere

**Comment by lolsas2** [comment]
> > > I tried recreating your issue but i'm getting
> > > > status code: 403
> > > > Cloudflare Blocked: Failed on url: https://recu.me/*****
> > 
> > 
> > What's wrong with this code? After this, program says " character is invalid.
> 
> When you run the program for the first time, it will create a config.json file in the working directory, just modify that one by just pasting in your links and headers. I would just delete your config.json file and start from scratch considering you just added random brackets everywhere

![Ekran Alıntısı](https://github.com/user-attachments/assets/6bd973a9-2ebd-41f3-9408-b429c19336f0)


this time, i signed in with opera, copy pasted cookies. then i get this error

**Comment by baconator696** [comment]
your daily view was already used,
currently you need a premium account to download entire videos from recurbate

**Comment by manavchaudhary1** [comment]
Or just create a new burner account.
