### ISSUE TITLE
Having a download speed issue

### ISSUE THREAD

**Issue by nef683** [baconator696/Recu-Download#14]
hii bro are you are the OG!!! are u  back on simpcity ??
the downloads are getting falied now at the start can u check its getting harder to download now

**Comment by nef683** [comment]
Error: client.Do:Get "https://f41.mediafront.ne, Retrying...
Downloading: 1.2%       Remaining: 2.2 days     123.4 KB/s
Error: io.ReadAll:context deadline exceeded (Client.Timeout or context cancellation while reading body)
Failed at 1.20%
Download Failed at line: 455

**Comment by nef683** [comment]
please make it back to normal i request you

**Comment by baconator696** [comment]
The error is from your download speed being too slow. Is your internet really that slow or was the server just having a bad day. If it is the prior, should I increase the timeout window, which is around 3 mins right now.
