### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Isheren** [baconator696/Recu-Download#15]
Hello I was wondering if you'd be able to show me how to do this download stuff. I'd compensate.

**Comment by baconator696** [comment]
shared this tutorial on a forum like 5 months ago lol, hope this helps

https://github.com/user-attachments/assets/8922d36b-1852-4d68-9751-9d6d8069fc3f

**Comment by Isheren** [comment]
Full disclosure. Me and gf used to stream. Our content is on the site. I'd
like it. Idc about pursuing legal I'll check it out shortly I'm really bad
at pc. But... I'll be DAMNED if I'm going to pay for OUR CONTENT while
they're making money

**Comment by baconator696** [comment]
you currently need a premium account to view/download videos, you can sign up for the 7 day trial for free though
