### ISSUE TITLE
Possible to download multiple videos at once?

### ISSUE THREAD

**Issue by solidwangz** [baconator696/Recu-Download#16]
Just curious and would like to know..is it possible to download more then 1 video at a time? and if so how would I go about that? would I just have to add the 2nd link on a seperate line under the URLS section?

**Comment by baconator696** [comment]
yes adding multiple links to the json will download the videos in parallel

for example:
````
{
	"urls": [
		"https://recu.me/user/video/9696969696/play",
		"https://recu.me/user/video/6969696969/play"
	],
	"header": {
		"Cookie": "",
		"User-Agent": ""
	}
}
```

**Comment by solidwangz** [comment]
Thank you. Do I need to add the cookie only once, yes I am assuming? and just need to add the video link on a seperate line I assume

**Comment by baconator696** [comment]
just one cookie

**Comment by solidwangz** [comment]
Ok thank you so much

**Comment by solidwangz** [comment]
I just wanted to ask, so I'm trying to download say 3 videos at once, and my config.json looks like this below, but after I save it and run the exe it just closes right away..Not sure why. Do I have to place the comma somewhere else after the link if I'm downloading more than 2 videos at once?

{
	"urls": [
		"https://recu.me/user/video/9696969696/play",
		"https://recu.me/user/video/6969696969/play"
                "https://recu.me/user/video/6969696969/play"
	],
	"header": {
		"Cookie": "",
		"User-Agent": ""
	}
}

**Comment by baconator696** [comment]
run the program through terminal, so the errror messages persist. Your json formating is wrong, misssing a comma after the second link
