### ISSUE TITLE
Speed Issue.

### ISSUE THREAD

**Issue by manavchaudhary1** [baconator696/Recu-Download#3]
```
manav@debian-pioneer:~/temp-go/Recu-Download$ go run main.go
Recu 
Downloading HTML: Complete
Getting Link to Playlist: Complete
Downloading Playlist: Complete
Downloading: 2.2%       Remaining: 4.4 hours    117.9 KB/s
```
As Mentioned in title and shown above , downloading speed is very slow , takes around 4 hours to download 40 min video .
I had make sure that i'm logged in & using high speed connection .
Don't know why but the videos on site also load very slowly .
Any solution .

**Comment by baconator696** [comment]
they throttle the speed based on the bitrate of the video, nothing you can do about it
