### ISSUE TITLE
Can free users use this program?

### ISSUE THREAD

**Issue by Tino23X** [baconator696/Recu-Download#5]
If free users can use it, sorry I don't understand Go programming and haven't read your source code, could you please tell me what value to fill in the Cookie? I have many options here and I don't know which one to choose, thank you.

**Comment by Tino23X** [comment]
As a free user, I'm wondering if I'm limited to partial downloads of videos. In my case, the download stopped at around 2% completion.

**Comment by baconator696** [comment]
as of  like last week, they only allow premium users to access videos, and if not logged in, only 5min window to download  a vid per day/IP

**Comment by sminato27** [comment]
is there any way to bypass these limitations as a free user?

**Comment by TeslaLyon** [comment]
> as of like last week, they only allow premium users to access videos, and if not logged in, only 5min window to download a vid per day/IP

I have not purchased a membership. Will I be banned if I log in to the same account from multiple IP addresses?

**Comment by Juju123-41** [comment]
> I've managed to find the solution, and I'm pleased to report that free users are indeed eligible to use the program. Additionally, I've discovered the methods for acquiring the cookie and user agent. https://github.com/baconator696/Recu-Download/issues/1#issuecomment-2119307932

any news about the solution | ?  
 I can tell you i ve been able to download 2 full videos of 90 mins but most of the times they just stop,   by being a non premium user i can imagine that the 1 daily video is still viable to download just i havent found the reason why they just stop.
