### ISSUE TITLE
Error: io.ReadAll:context deadline exceeded

### ISSUE THREAD

**Issue by nexter46** [baconator696/Recu-Download#6]
Error: io.ReadAll:context deadline exceeded (Client.Timeout or context cancellation while reading body)
Failed at 25.27%
Download Failed at line: 2919
keeps getting in new update

or else it will show like this
Error: io.ReadAll:read tcp **here my ip address has came**:58037->, Retrying...

2errors showing

**Comment by baconator696** [comment]
that's because the server didn't serve the video in the given amount of time (60 seconds), I made a change when it retries, the timeout will increase to a max of 130 seconds after all retries
